### ISSUE TITLE
Unable to run a cluster with spot_duration provisioning

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla-cluster-tests#2562]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master

### Logs
```
< t:2020-08-27 09:24:47,372 f:cluster.py      l:2849 c:sdcm.cluster         p:INFO  > Cluster sarna-root-db-cluster-9490739c (AMI: ['ami-04e170e18ce12fefc'] Type: i3.large): Init nodes
< t:2020-08-27 09:24:48,032 f:ec2_client.py   l:141  c:sdcm.ec2_client      p:INFO  > Calculating spot price based on OnDemand price
< t:2020-08-27 09:24:48,809 f:ec2_client.py   l:146  c:sdcm.ec2_client      p:INFO  > Spot bid price: {'max': 0.156, 'desired': 0.0936}
< t:2020-08-27 09:24:48,809 f:ec2_client.py   l:97   c:sdcm.ec2_client      p:INFO  > Sending spot request with params: {'DryRun': False, 'InstanceCount': 1, 'Type': 'one-time', 'SpotPrice': '0.0936', 'LaunchSpecification': {'ImageId': 'ami-04e170e18ce12fefc', 'InstanceType': 'i3.large', 'NetworkInterfaces': [{'DeviceIndex': 0, 'SubnetId': 'subnet-0eccb01ed2a898832', 'AssociatePublicIpAddress': True, 'Groups': ['sg-083f6dce0c5ff5088']}], 'IamInstanceProfile': {'Name': 'qa-scylla-manager-backup-instance-profile'}, 'BlockDeviceMappings': [{'DeviceName': '/dev/sda1', 'Ebs': {'VolumeSize': 30, 'VolumeType': 'gp2'}}], 'KeyName': 'scylla-qa-ec2', 'UserData': 'eyJzY3lsbGFfeWFtbCI6IHsiY2x1c3Rlcl9uYW1lIjogInNhcm5hLXJvb3QtZGItY2x1c3Rlci05NDkwNzM5YyIsICJhdXRvX2Jvb3RzdHJhcCI6IGZhbHNlfSwgInN0YXJ0X3NjeWxsYV9vbl9maXJzdF9ib290IjogZmFsc2UsICJwb3N0X2NvbmZpZ3VyYXRpb25fc2NyaXB0IjogIkl5RXZZbWx1TDJKaGMyZ0tjM1ZrYnlCelpXUWdMV2tnSjNNdkkwMWhlRk5sYzNOcGIyNXpJRndvTGlwY0tTUXZUV0Y0VTJWemMybHZibk1nTVRBd01DOG5JQzlsZEdNdmMzTm9MM056YUdSZlkyOXVabWxuQ25OMVpHOGdjMlZrSUMxcElDZHpMeU5OWVhoVGRHRnlkSFZ3Y3lCY0tDNHFYQ2trTDAxaGVGTjBZWEowZFhCeklEWXdMeWNnTDJWMFl5OXpjMmd2YzNOb1pGOWpiMjVtYVdjS2MzVmtieUJ6WldRZ0xXa2dKM012STB4dloybHVSM0poWTJWVWFXMWxJRndvTGlwY0tTUXZURzluYVc1SGNtRmpaVlJwYldVZ01UVnpMeWNnTDJWMFl5OXpjMmd2YzNOb1pGOWpiMjVtYVdjS2MzVmtieUJ6ZVhOMFpXMWpkR3dnY21WemRHRnlkQ0J6YzJoa0NncHpaV1FnTFdrZ0xXVWdKM012WGx3cVcxczZZbXhoYm1zNlhWMHFjMjltZEZ0Yk9tSnNZVzVyT2wxZEttNXdjbTlqVzFzNllteGhibXM2WFYwcU5EQTVOaThxWEhSY2RITnZablJjZEc1d2NtOWpYSFJjZEhWdWJHbHRhWFJsWkM4bklGd0tMMlYwWXk5elpXTjFjbWwwZVM5c2FXMXBkSE11WkM4eU1DMXVjSEp2WXk1amIyNW1DbVZqYUc4Z0xXVWdKeXBjZEZ4MGFHRnlaRngwYm5CeWIyTmNkRngwZFc1c2FXMXBkR1ZrSnlBK1BpQXZaWFJqTDNObFkzVnlhWFI1TDJ4cGJXbDBjeTVrTHpJd0xXNXdjbTlqTG1OdmJtWUsifQ=='}, 'ValidUntil': datetime.datetime(2020, 8, 27, 9, 34, 48, 809761), 'BlockDurationMinutes': 180}
< t:2020-08-27 09:24:49,533 f:ec2_client.py   l:167  c:sdcm.ec2_client      p:INFO  > Waiting for spot instances...
< t:2020-08-27 09:24:55,018 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > 2020-08-27 09:24:55.006: (TestFrameworkEvent Severity.ERROR), source=BuildClusterTest.SetUp() 
< t:2020-08-27 09:24:55,018 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > exception=Failed to get spot instances: price-too-low

```

### Description

I'm trying to boot a cluster of weak db instances (i3.large) and good loader instances (c5.9xlarge) in order to run some overload scenarios. The following yaml file works fine with spot_low_price, but fails every single time with spot_duration provisioning:

```yaml
test_duration: 120 

#number of nodes in the cluster
n_db_nodes: 1
#number of loadres in the cluster
n_loaders: 2
#number of monitors - we will probably wont touch it.
n_monitor_nodes: 1

instance_type_db: 'i3.large'
nemesis_class_name: 'NoOpMonkey'
nemesis_filter_seeds: false

instance_type_loader: 'c5.9xlarge'

scylla_version: '4.1'
region_name:
    - us-east-1

user_prefix: 'sarna'

instance_provision: 'spot_duration'
logs_transport: 'ssh'
ip_ssh_connections: 'public'
post_behavior_db_nodes: "keep"
post_behavior_loader_nodes: "keep"
post_behavior_monitor_nodes: "keep"

backtrace_decoding: false

```

`spot_low_price` notoriously kills one of the nodes within minutes, which makes the test a pain. I can always work around the issue by using `on_demand`, but `spot_duration` would be a nice compromise between pricing and stability - I only want the machines to be up for 1-2 hours.

### Steps to Reproduce

1. Use the yaml above and run `./docker/env/hydra.sh run-test build_cluster_test.BuildClusterTest.test_build -c test-cases/overload.yaml -b aws`
2. Observe the test failing after a couple of seconds with `too-low-price`

**Expected behavior:** a running cluster

**Actual behavior:** a failed run
