### ISSUE TITLE
ChaosMonkey with probability distribution on disruptions

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla-cluster-tests#2732]
ChaosMonkey chooses disruptions with uniform distribution (each disruption has an equal probability of being chosen, `1/n` where `n` is the number of different disruption methods). For tests which target specific types of failures it would be nice to have a nemesis where we can specify an arbitrary [categorical distribution](https://en.wikipedia.org/wiki/Categorical_distribution).

Say, for example, I'd like my nemesis to run:
- `disrupt_network_random_interruptions` 2 out of 10 times,
- `disrupt_remove_node_then_add_node` 3 out of 10 times,
- `disrupt_grow_shrink_cluster` 5 out of 10 times.

To do that, I would specify in my test yaml something like:
```yaml
nemesis_class_name: 'ChaosMonkeyWithDistribution'
nemesis_disruption_distribution:
    network_random_interruptions: 2
    disrupt_remove_node_then_add_node: 3
    disrupt_grow_shrink_cluster: 5
```

`ChaosMonkey` would be equivalent to `ChaosMonkeyWithDistribution` with each disruption listed with the same number.

An unlisted disruption, or one with `0` specified, would never be executed.

**Comment by roydahan** [comment]
The UX here is a bit problematic.
Would you want to start list all types of disruptions and their probability?
And every change in 1 will require a change in all of them.

What is the actual motivation behind it?
Why would you want a specific one to be more probable than others?
(I can understand why to not include some disruptions).

**Comment by roydahan** [comment]
CC @bentsi & @fruch for more insights.

**Comment by kbr-** [comment]
I'd like to run a bunch of different disruptions during a single test, but I want to focus on some of them more than the others. For example, it's nice to have a major compaction executed from time to time, but it's not as important as bootstrapping a new node, say (at least for  testing CDC we'd like to have a bunch of topology changes during the test).

Note that this isn't totally different from the existing nemeses, it's a generalization. With careful implementation ChaosMonkey, LimitedChaosMonkey, ScyllaCloudLimitedChaosMonkey etc. could be defined in terms of this new nemesis.

**Comment by roydahan** [comment]
I understand that, and we also debated about this in the past.
However, this approach is not that useful for the long term, especially when we add more and more nemesis.

The LimitedChaosMonkey is an old approach for fixed list of nemesis, also not the best approach for long term but very easy one.

The "DisruptiveNemesis" and "NonDisruptive" are those that we can easily maintain for long term.

Maybe, we can do the same with "ranking" each nemesis and then calculate the probability by ranking score.
or by Classes (group of nemesis) that each get a rank.
(We have a task in the backlog to have all nemesis in set of classes).

**Comment by bentsi** [comment]
@kbr- Agree with Roy, UX is problematic. How many tests like this do you want to develop? If it is one/two tests better to add this as a Monkey class and add an infra in the Nemesis base class. 
Adding test YAML support for this is more complex and error-prone, I prefer not to get into this.

**Comment by kbr-** [comment]
@roydahan @bentsi I can do it without the YAML and have the distribution passed into the Monkey's constructor, so the test developer must explicitly initialize it.

Nevertheless, I made a POC implementation that uses SCTConfiguration to get the distribution, but it can be easily modified to get the dist from constructor: https://github.com/kbr-/scylla-cluster-tests/commits/distributed_monkey
maybe you'll like it

**Comment by kbr-** [comment]
If you think the list of different disruptions one has to list is too big, I could use different default behavior, e.g. if a disruption is not listed it gets default value `10`.

**Comment by kbr-** [comment]
You can see here:
https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/feature-cdc-replication-longevity/18/console
how the new nemesis runs
it is configured as follows:
```
nemesis_class_name: 'DistributedMonkey'
nemesis_interval: 5
nemesis_disruption_distribution:
  nodetool_decommission: 5
  terminate_and_replace_node: 5
  grow_shrink_cluster: 5
  remove_node_then_add_node: 5
  decommission_streaming_err: 5
  network_random_interruptions: 2
  network_block: 2
  network_start_stop_interface: 2
  stop_wait_start_scylla_server: 1
  stop_start_scylla_server: 1
  restart_then_repair_node: 1
  hard_reboot_node: 1
  multiple_hard_reboot_node: 1
  soft_reboot_node: 1
  restart_with_resharding: 1
  destroy_data_then_repair: 1
  destroy_data_then_rebuild: 1
  nodetool_drain: 1
  kill_scylla: 1
  no_corrupt_repair: 1
  major_compaction: 1
  nodetool_refresh: 1
  nodetool_enospc: 1
  truncate: 1
  truncate_large_partition: 1
  delete_10_full_partitions: 1
  delete_by_rows_range: 1
  abort_repair: 1
  snapshot_operations: 1
  rebuild_streaming_err: 1
  repair_streaming_err: 1
  memory_stress: 1
```
