### ISSUE TITLE
enable append_scylla_yaml for kubernetes backend

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#2746]
Could be done via configmap:

create config map:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla-config
data:
  scylla.yaml:
    ... configuration ...
```
