### ISSUE TITLE
[K8S] Scylla-operator upgrade scenario doesn't catch failure upgrading `ScyllaCluster` object and continues to work with old one

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#6943]
The upgrade of the scylla-operator from `v1.10.0` version to the `v1.11.0-rc.0` failed to trigger the `ScyllaCluster` object upgrade, then our test didn't catch it and continued working with old state of the `ScyllaCluster` object.
So, it comes out that the upgrade was not completed as it should.

Error that should have been caught:
```
status:
  conditions:
...
  - lastTransitionTime: "2023-10-05T22:33:32Z"
    message: 'can''t apply statefulset update: can''t update apps/v1, Kind=StatefulSet
      "scylla/sct-cluster-us-east1-b-us-east1": StatefulSet.apps "sct-cluster-us-east1-b-us-east1"
      is invalid: spec: Forbidden: updates to statefulset spec for fields other than
      ''replicas'', ''ordinals'', ''template'', ''updateStrategy'', ''persistentVolumeClaimRetentionPolicy''
      and ''minReadySeconds'' are forbidden'
    observedGeneration: 4
    reason: Error
    status: "True"
    type: StatefulSetControllerDegraded
```

Scylla pods are unexpectedly old:
```
scylla-operator    scylla-operator-585b8b677c-wv4gc     1/1    Running    1 (8m25s ago)   8m26s   10.0.2.67
scylla-operator    scylla-operator-585b8b677c-xxzqr     1/1    Running    1 (8m26s ago)   8m33s   10.0.1.194
scylla-operator    webhook-server-cffd5fd54-cbmdx       1/1    Running    0               8m13s   10.0.2.11
scylla-operator    webhook-server-cffd5fd54-njmrh       1/1    Running    0               8m33s   10.0.1.61
scylla             sct-cluster-us-east1-b-us-east1-0    2/2    Running    1 (113m ago)    115m    10.0.1.199
scylla             sct-cluster-us-east1-b-us-east1-1    2/2    Running    1 (110m ago)    112m    10.0.0.50
scylla             sct-cluster-us-east1-b-us-east1-2    2/2    Running    1 (106m ago)    108m    10.0.2.86
scylla             sct-cluster-us-east1-b-us-east1-3    2/2    Running    1 (4m59s ago)   7m23s   10.0.3.117
```

These old Scylla pods have following old init container image version:
```
  hostname: sct-cluster-us-east1-b-us-east1-0
  initContainers:
  - command:
    - /bin/sh
    - -c
    - cp -a /usr/bin/scylla-operator /mnt/shared
    image: scylladb/scylla-operator:1.10.0
```

To start catching such errors we should check following:
- `metadata.generation` changes/increments
- `status.condition` values for the presence of errors
- optional: any approach for making sure that Scylla pods get recreated
- optional: trigger forced `roll-out` of Scylla pods

Ref operator bug: https://github.com/scylladb/scylla-enterprise/issues/3680

After the implementation of the fix for this bug we should run following scenarios:
- `v1.10.x` -> `v1.11.0` -> must fail
- `v1.10.x` -> `v1.11.1+` (when gets available) -> must work
- `v1.11.0` -> `v1.11.1+` (when gets available) -  must work

## Installation details

Kernel Version: 5.10.192-183.736.amzn2.x86_64
Scylla version (or git commit hash): `2023.1.1-20230906.f4633ec973b0` with build-id `b454e7a22f80cf71a33b2f39e47127225e8fbc13`

Operator Image: scylladb/scylla-operator:1.10.0
Operator Helm Version: v1.10.0
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/stable
Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: `eu-north-1`)

Test: `upgrade-operator-k8s-eks`
Test id: `06a561b2-fc78-4e33-bbce-ac1d9f12f0a7`
Test name: `scylla-operator/operator-1.11/upgrade/upgrade-operator-k8s-eks`
Test config file(s):

- [kubernetes-operator-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/0ebb9363e3e989e2ef5097caaabb112319307511/test-cases/scylla-operator/kubernetes-operator-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 06a561b2-fc78-4e33-bbce-ac1d9f12f0a7`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=06a561b2-fc78-4e33-bbce-ac1d9f12f0a7)
- Show all stored logs command: `$ hydra investigate show-logs 06a561b2-fc78-4e33-bbce-ac1d9f12f0a7`

## Logs:
- **kubernetes-06a561b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/06a561b2-fc78-4e33-bbce-ac1d9f12f0a7/20231005_224028/kubernetes-06a561b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/06a561b2-fc78-4e33-bbce-ac1d9f12f0a7/20231005_224028/kubernetes-06a561b2.tar.gz)
- **db-cluster-06a561b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/06a561b2-fc78-4e33-bbce-ac1d9f12f0a7/20231005_224028/db-cluster-06a561b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/06a561b2-fc78-4e33-bbce-ac1d9f12f0a7/20231005_224028/db-cluster-06a561b2.tar.gz)
- **sct-runner-events-06a561b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/06a561b2-fc78-4e33-bbce-ac1d9f12f0a7/20231005_224028/sct-runner-events-06a561b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/06a561b2-fc78-4e33-bbce-ac1d9f12f0a7/20231005_224028/sct-runner-events-06a561b2.tar.gz)
- **sct-06a561b2.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/06a561b2-fc78-4e33-bbce-ac1d9f12f0a7/20231005_224028/sct-06a561b2.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/06a561b2-fc78-4e33-bbce-ac1d9f12f0a7/20231005_224028/sct-06a561b2.log.tar.gz)
- **loader-set-06a561b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/06a561b2-fc78-4e33-bbce-ac1d9f12f0a7/20231005_224028/loader-set-06a561b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/06a561b2-fc78-4e33-bbce-ac1d9f12f0a7/20231005_224028/loader-set-06a561b2.tar.gz)
- **monitor-set-06a561b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/06a561b2-fc78-4e33-bbce-ac1d9f12f0a7/20231005_224028/monitor-set-06a561b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/06a561b2-fc78-4e33-bbce-ac1d9f12f0a7/20231005_224028/monitor-set-06a561b2.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-1.11/job/upgrade/job/upgrade-operator-k8s-eks/2/)
[Argus](https://argus.scylladb.com/test/5dc3b95e-1d33-428f-8263-cab9e27e5706/runs?additionalRuns[]=06a561b2-fc78-4e33-bbce-ac1d9f12f0a7)
</details>
