### ISSUE TITLE
Consider replacing syslog-ng with vector.dev

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#7010]
Vector claims to be very fast and capable to do what we need:
https://vector.dev/

IIUC, we may also integrate it with scylla at some point (maybe as a source), however, we can start in SCT to examine if it can handle the high load logs issue, especially since it has few capabilities we can use on the source side like filter.
These capabilities called "transforms" and filter is one of them:
https://vector.dev/docs/reference/configuration/transforms/filter/

It means, we can deploy vector on all nodes with the configuration we want to filter on the client side (some polluting messages we don't want the handle on the sct-runner side e.g. "Failed to apply view".

credit to @mykaul.

### TODOs

- [x] installation on node
- [x] docker base aggregator on sct-runner (like we have for syslog-ng)
- [x] configuration and handling of the communication (tunneling as needed)

**Comment by fruch** [comment]
We can do client filtering with syslog-ng

We don't know if our bottle neck is syslog-ng, it's probably the fact we are reading all lines in python, and doing a big list of regex ontop of them

Moving those regex into a client might help, but would take CPU cycles from scylla, that also means we won't have logging of them at all

Also we should stop writing db nodes logs in sct.log, it's lots of duplications, and slowdowns

**Comment by roydahan** [comment]
> We can do client filtering with syslog-ng
> 

The question is how good it is...
> We don't know if our bottle neck is syslog-ng, it's probably the fact we are reading all lines in python, and doing a big list of regex ontop of them
> 
We kind of know it's both, depends on the scenario.
We already saw cases that syslog dropped messages.
When we have high load of messages, it's probably the python that handles all these messages.

> Moving those regex into a client might help, but would take CPU cycles from scylla, that also means we won't have logging of them at all
> 
We won't filter too many, all very few that we know causing us issues.
Anyway, I'm sure their filter will be much more efficient on the client-side.

> Also we should stop writing db nodes logs in sct.log, it's lots of duplications, and slowdowns

I disagree.

**Comment by fruch** [comment]
@roydahan 

you think there is still a need for this one ? 

is the cloud really completely move to that one ?

**Comment by roydahan** [comment]
I don't know, do you think the "bad packet" issue is still caused by our parsing?

We can check with them if they did and how does it work for them.

**Comment by mykaul** [comment]
The cloud is now using Vector, btw.

**Comment by fruch** [comment]
> I don't know, do you think the "bad packet" issue is still caused by our parsing?

I preety sure it's not our parsing, just out inability to preserve CPU for the sshd

We have a workaround for those issues, that seems to be working for now

It was never related to our log parsing, AFAIK

> 
> We can check with them if they did and how does it work for them.
> 

O.k. to only real reason for us to switch is aligning with scylla-cloud.

**Comment by fruch** [comment]
I've  played a bit with vector yesterday, 

I've checked the configuration capabilities

something like the following, can generate same output logs as we expect in SCT:
```yaml
data_dir: "/var/lib/vector"

sources:
  journald:
    type: journald

transforms:
  format_logs:
    type: remap
    inputs:
      - journald
    source: |
       .timestamp = format_timestamp!(.timestamp, "%Y-%m-%dT%H:%M:%S%.3f")

       .level = upcase(to_syslog_level!(to_int!(.PRIORITY)))
       desired_length = 7
       original = to_string(.level)
       original_length = length(original)

       pad_count = desired_length - original_length
       pad_count = if pad_count > 0 { pad_count } else { 0 }

       # Static array of 20 spaces
       pad_array = [" "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "]

       #Slice the array to desired pad length and join
       padding = join!(slice!(pad_array, 0, pad_count), "")

       .level_padded = padding + "!" + .level

       .message = join!([.timestamp, .host, .level_padded, "|" , .SYSLOG_IDENTIFIER, .message], " ")

sinks:
  console:
    type: console
    inputs:
      - format_logs
    encoding:
      codec: json
      # only_fields: [
  file_by_host:
    type: file
    inputs:
      - format_logs
    path: /tmp/vector-{{ .host }}.log
    encoding:
      codec: text

```
