### ISSUE TITLE
SCT defines the same aws_region for all nodes of multiDC cluster in scylla.yaml (kms_hosts:auto section)

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-cluster-tests#9025]
During nodes configuration (config_setup -> proposed_scylla_yaml) SCT defines the same `aws_region` for all nodes of multiDC cluster in scylla.yaml:
```
kms_hosts:
  auto:
    aws_region: us-east-1
    aws_use_ec2_credentials: true
    master_key: alias/testid-10224f75-e3b0-4879-a336-e1293bcb2d77
```
For my case, I have multiDC cluster with nodes in two regions - `us-east-1` and `us-west-2`. You can take a look into at scylla.yaml files for [run](https://argus.scylladb.com/tests/scylla-cluster-tests/6a48fe73-69f0-463e-986a-cc7c4ade6cdc) - `aws_region: us-east-1` is defined for all nodes.

I suppose this issue was introduced [here](https://github.com/scylladb/scylla-cluster-tests/commit/44ce384eaf6c7366bebe9210c2ba2b3fb2c1eca6#diff-d2939618bee56b9b221c3d9a1e8403478691c8196009d6dbfccc6c5f13ae1951R63) since changing the [line](https://github.com/scylladb/scylla-cluster-tests/blob/master/sdcm/cluster.py#L518) from:
```
append_scylla_yaml["kms_hosts"][kms_host_name]["aws_region"] = self.vm_region
```
to:
```
append_scylla_yaml["kms_hosts"][kms_host_name]["aws_region"] = self.region
```
resolved configuration issue.
